### ISSUE TITLE
Shall we delete /docs?

### ISSUE THREAD

**Issue by Nautigsam** [uh-cs-iotlab/node-iothub#9]
Since we have the gh-pages branch, maybe this is not necessary anymore.

**Comment by jmineraud** [comment]
Just wait a bit, i have not updated everything
On 7 Apr 2016 12:50, "Aurélien Bertron" notifications@github.com wrote:

Since we have the gh-pages branch, maybe this is not necessary anymore.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/uh-cs-iotlab/solmuhub/issues/9

**Comment by sklvarjo** [comment]
The gh-pages still need clarification on the users and roles. It can be easily seen that you can attach a role to a feed but how to add a user to a role? Also how to use access tokens is missing from the gh-pages.

**Comment by jmineraud** [comment]
Ok, i will update the doc when I have a little time
